### ISSUE TITLE
邮箱的密码首字符是&的时候会出错

### ISSUE THREAD

**Issue by lord63** [guo-yu/kindle#2]
在设置发送邮箱的时候，我的邮箱密码中的第一个字符是&，然后貌似就会错以为是将命令丢到后台执行，无法正常运行的样子。
![002](https://cloud.githubusercontent.com/assets/5268051/3351624/6d31bd94-fa16-11e3-8eb7-747f96731f86.png)

node：v0.10.29
Linux Mint 16

**Comment by turingou** [comment]
从 stdin 读取确实是个问题，你试试看加上单引号。
或许从配置文件读取是个更明智的选择
